- name: print the variables from inventory
  hosts: local
  connection: local
  tasks:
  - name: print the variables from inventory
    ansible.builtin.debug:
      msg: " name is {{ NAME }} and age is {{ AGE }}"