- name: variable preferences from playbook
  hosts: local
  connection: local
  vars:
    GREETING: "Hello from Play"
  vars_files:
  - course.yaml
  # vars_prompt:
  #   - name: GREETING 
  #     prompt: Enter the Greeting
  #     private: false

  tasks:
  - name: print the Greeting
    # vars:
    #   GREETING: "Hello from Task"
    ansible.builtin.debug:
      msg: "print the {{ GREETING }} "
