- name: var prefernces
  hosts: local
  connection: local
  vars:
    # GREETING: Hello-from-vars
  vars_files:
  # - course.yaml 
  vars_prompt:
    # - name: GREETING
    #   prompt: Please enter greetings from prompt
    #   private: false
  tasks:
  - name: varibales from the tasks
    # vars:
    #   GREETING: Hello-from-task
    ansible.builtin.debug:
      msg: " hello gretting {{ GREETING }}"
