- name: install multiple packages in ansible
  hosts: frontend
  become: yes
  tasks:
  - name: install all packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
      - nginx
      - git
      - python3

  - name: start all packages
    ansible.builtin.service:
      name: "{{ item }}"
      state: started
      enabled: yes
    loop:
    - nginx
  
  