- name: install packages
  hosts: frontend
  become: yes
  tasks: 
  - name: install packages
    ansible.builin.dnf:
      - name: "{{ item }}"
        state: present
    loop:
    - nginx
    - zip
    - mysql 