- name: functions in ansible
  hosts: local
  connection: local
  vars:
    persons: "ramesh, suresh, madhu"
  tasks:
  - name: printing the functions in ansible
    ansible.builtin.debug:
      msg: " my name is {{ person | default('Nagalakshmi') }}"

  - name: printing the person names
    ansible.builtin.debug:
      msg: " {{ persons | split(',')}}"

  - name: convert dict to list
    vars:
      course:
        title: devops
        time: 180hr

    ansible.builtin.debug:
      msg: "{{ course | dict2items}}"

  - name: convert list to dict
    vars:
      names:
        - { 'key':'ramesh', 'value':'male' }
        - { 'key':'lakshmi', 'value':'female' }
    ansible.builtin.debug:
      msg: "{{ names | items2dict }}"

  - name: convert lower case to upper case
    vars:
      name:"devops with aws"
    ansible.builtin.debug:
      msg: "{{ name | upper }}"
