- name: command and shell mdule
  hosts: frontend
  tasks:
  - name: use shell module
    ansible.builtin.shell: "ls -ltr > /tmp/output.txt"
    register: shell_output

  - name: print the shell module output
    ansible.builtin.debug:
      msg: " {{ shell_output }}"

  - name: use command module
    ansible.builtin.command: "ls -ltr"
    register: command_output

  - name: print the shell module output
    ansible.builtin.debug:
      msg: " {{ command_output }}"