- name: create ec2 and r53 records
  connection: local
  hosts: local
  vars:
    - mysql
    - backend
    - frontend 
    subnet_id : subnet-0a48670d714d35284
    sg_id: sg-08e3733ce77305f2f
    image_id: ami-0220d79f3f480ecf5
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: "{{ image_id}}"
      tags:
      Environment: "{{ item }}"
    loop: "{{ instance }}"