- name: install nginx using ansible facts
  hosts: frontend
  become: yes
  tasks:
  - name: install nginx using dnf
    ansible.builtin.dnf:
      name: nginx
      state: present
  - name: Run and enable nginx
    ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes