- tag:Name: install nginx
  hosts: aws_frontend
  #serial: 4
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: present

  - name: run and enable nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes