- name: create ec2 and r53 records
  connection: local
  hosts: local
  vars:
    instances:
    - mysql
    - backend
    - frontend
    subnet_id: subnet-0ac856ba4ad9d5d06
    sg_id: sg-0033ecf0c0f6062e4
    zone: lakshmireddy.site
  tasks:
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: t3.micro
      image_id: ami-09c813fb71547fc4f
      tags:
        Name: "{{ item }}"
    loop: "{{ instances }}"
    register: ec2_output
  - name: print the ec2 ec2_output
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"

  - name: create r53 records
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ item.item }}.{{ zone }}"
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      wait: true
      overwrite: true
    loop: {{amazon.aws.results}}
