[frontend]
54.147.229.234 COURSE=python TIME=60hrs  TRAINER=Siva  ansible_user=ec2-user  ansible_password=DevOps321
52.90.162.131 COURSE=java TIME=10hrs  TRAINER=Siva ansible_user=ec2-user  ansible_password=DevOps321


[backend]
54.147.229.234
52.90.162.131


[database]
54.147.229.234
52.90.162.131

[local]
localhost

[local:vars]
COURSE= DevOps
TIME= 120hrs
TRAINER= Siva
GREETING="hello from inventory" 